#config_version=6

hardware:
  platform: visual_pinball_engine

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

vpe:
  debug: True

switches:
  s_trough1:
    number: 1
  s_trough2:
    number: 2
  s_trough3:
    number: 3
  s_trough4:
    number: 4
  s_left_flipper:
    number: 5
    tags: left_flipper
  s_right_flipper:
    number: 6
    tags: right_flipper
  s_start:
    number: 7
    tags: start
  s_plunger_lane:
    number: 8
  s_plunger_lane_exit:
    number: 9
    tags: playfield_active

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4

coils:
  c_flipper_left:
    number: 0
    allow_enable: True
  c_flipper_right:
    number: 1
    allow_enable: true
  c_trough_eject:
    number: 2
    default_pulse_ms: 20

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4
    eject_coil: c_trough_eject
    eject_targets: bd_plunger
    tags: trough, home, drain
    eject_timeouts: 3s
    debug: true
  bd_plunger:
    ball_switches: s_plunger_lane
    mechanical_eject: true
    eject_timeouts: 3s

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_right_flipper