#config_version=5

hardware:
  platform: visual_pinball_engine

vpe:
  debug: True

switches:
  s_left_flipper:
    number: 11
    tags: left_flipper
  s_right_flipper:
    number: 12
    tags: right_flipper
  s_trough1:
    number: 1
  s_trough2:
    number: 2
  s_trough3:
    number: 3
  s_trough4:
    number: 4
  s_trough5:
    number: 5
  s_trough6:
    number: 6
  s_trough_jam:
    number: 7
  s_plunger:
    number: 10

coils:
  c_flipper_left_main:
    number: 0
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 1
    default_pulse_ms: 20
    allow_enable: true
  c_flipper_right_main:
    number: 2
  c_flipper_right_hold:
    number: 3
    allow_enable: true
  c_trough_eject:
    number: 4

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: true
  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3