#config_version=5

hardware:
  platform: visual_pinball_engine

playfields:
  playfield:
    tags: default
    default_source_device: None

vpe:
  debug: True

switches:
  s_left_flipper:
    number: 0
    tags: left_flipper
  s_right_flipper:
    number: 1
    tags: right_flipper

coils:
  c_flipper_left_main:
    number: 0
  c_flipper_left_hold:
    number: 1
    allow_enable: true
  c_flipper_right_main:
    number: 2
  c_flipper_right_hold:
    number: 3
    allow_enable: true


flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3



#hardware:
#  platform: visual_pinball_engine
#
#playfields:
#  playfield:
#    tags: default
#    default_source_device: None
#
#vpe:
#  debug: True
#
#switches:
#  s_sling:
#    number: 0
#  s_flipper:
#    number: 3
#  s_test:
#    number: 6
#
#coils:
#  c_sling:
#    number: 0
#  c_flipper:
#    number: 1
#    allow_enable: True
#  c_test:
#    number: 2
#    allow_enable: True
#
#lights:
#  test_light1:
#    number: 0
#  test_light2:
#    number: 1
#
#autofire_coils:
#  ac_slingshot_test:
#    coil: c_sling
#    switch: s_sling
#
#flippers:
#  f_test:
#    main_coil: c_flipper
#    activation_switch: s_flipper
#
