name: Build
on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: windows-latest
            rid: win-x86
          - os: macos-latest
            rid: osx-x64
          - os: ubuntu-latest
            rid: linux-x64
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          dotnet build -c Release -r ${{ matrix.rid }} -p:InstallYetAnotherHttpHandler=false
      - run: |
          mkdir -p tmp/Plugins
          cp -r Plugins/${{ matrix.rid }} tmp/Plugins
      - uses: actions/upload-artifact@v4
        with:
          name: Plugins-${{ matrix.rid }}
          path: tmp
  install-yetanotherhttphandler:
    name: Install YetAnotherHttpHandler
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: dotnet build /t:InstallYetAnotherHttpHandler
        - run: |
            mkdir -p tmp/YetAnotherHttpHandler
            cp -r YetAnotherHttpHandler tmp/YetAnotherHttpHandler
        - uses: actions/upload-artifact@v4
          with:
            name: YetAnotherHttpHandler
            path: tmp

  dispatch:
    runs-on: ubuntu-latest
    needs: [ build, install-yetanotherhttphandler ]
    if: github.repository == 'VisualPinball/VisualPinball.Engine.Mpf' && github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: build-complete
          client-payload: '{"artifacts_run_id": "${{ github.run_id }}"}'
