name: Build
on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          dotnet build -c Release
      - run: |
      - run: |
          mkdir -p tmp/Runtime/GrpcInterface/Generated
          cp -r Plugins tmp
          cp -r YetAnotherHttpHandler tmp
          cp -r Runtime/GrpcInterface/Generated/* tmp/Runtime/GrpcInterface/Generated/
      - uses: actions/upload-artifact@v4
        with:
          name: Build-Artifacts
          path: tmp

  dispatch:
    runs-on: ubuntu-latest
    needs: [ build]
    if: github.repository == 'VisualPinball/VisualPinball.Engine.Mpf' && github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: build-complete
          client-payload: '{"artifacts_run_id": "${{ github.run_id }}"}'
