name: Publish
on:
  repository_dispatch:
    types: [ release-complete ]

jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v4
        with:
          workflow: build
          run_id: ${{ github.event.client_payload.artifacts_run_id }}
      - name: Publish
        run: |
          echo "//registry.visualpinball.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
