name: Publish
on:
  repository_dispatch:
    types: [ release-complete ]

jobs:
  registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.visualpinball.org'
      - uses: actions/download-artifact@v4
        with:
          name: Plugins
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.client_payload.artifacts_run_id }}
      - name: Publish
        run: |
          ls -laR .
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}